In [1]:
import numpy as np

In [4]:
first_numpy_array= np.array([1,2,3,4])

In [6]:
print (first_numpy_array)

[1 2 3 4]


In [7]:
array_with_zeros = np.zeros((3,3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
array_with_ones = np.ones((3,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np_arange = np.arange(12)

In [13]:
print(np_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [16]:
np_arange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
np_linespace = np.linspace(1,6,5)

In [22]:
print(np_linespace)

[1.   2.25 3.5  4.75 6.  ]


In [23]:
numpy_arr =np.array([x for x in range(1,10)])

In [24]:
numpy_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
numpy_arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
numpy_arr =np.array([x for x in range(1,13)])

In [29]:
numpy_arr.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [31]:
numpy_arr.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [32]:
numpy_arr.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [35]:
A= np.array([[1,2,7],[3,4,2]])
B= np.array([5,6,9])

In [37]:
A

array([[1, 2, 7],
       [3, 4, 2]])

In [38]:
B

array([5, 6, 9])

In [39]:
np.add(A,B)

array([[ 6,  8, 16],
       [ 8, 10, 11]])

In [40]:
np.subtract(B,A)

array([[4, 4, 2],
       [2, 2, 7]])

In [41]:
np.multiply(A,B)


array([[ 5, 12, 63],
       [15, 24, 18]])

In [42]:
np.divide(A,B)

array([[0.2       , 0.33333333, 0.77777778],
       [0.6       , 0.66666667, 0.22222222]])

In [43]:
np.power(A,B)

array([[       1,       64, 40353607],
       [     243,     4096,      512]], dtype=int32)

In [45]:
x = np.array([i for i in range(10)])

In [46]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
np.where(x%2==0,'even','odd')

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd'], dtype='<U4')

In [49]:
numpy_arr = np.array([[1,2,3],[7,0,2],[6,7,3]])

In [51]:
np.max(numpy_arr)

7

In [52]:
np.min(numpy_arr)

0

In [54]:
np.amin(numpy_arr,axis=0)

array([1, 0, 2])

In [55]:
numpy_arr

array([[1, 2, 3],
       [7, 0, 2],
       [6, 7, 3]])

In [56]:
arr_1d= np.array([1,2,3])
arr_2d= np.array([[1,8,9],[2,6,0]])
arr_3d= np.array([[2,3,6],[2,6,8],[3,5,1],[9,0,4,]])

In [58]:
arr_1d

array([1, 2, 3])

In [60]:
arr_1d[0:]

array([1, 2, 3])

In [61]:
arr_1d[-1:]

array([3])

In [62]:
arr_2d[1,1:]

array([6, 0])